#!/usr/bin/env python3
"""Builds the paste-ready Supabase email templates from _layout.html.

Every email shares one layout (icon, fonts, colours, footer) so they can't
drift apart; each template below only supplies its own words and action.
Edit here or in _layout.html, then run:  python3 supabase/email-templates/build.py
and paste the generated <name>.html into the Supabase dashboard
(Authentication -> Email Templates). No CLI on this machine.

Output is pure ASCII (non-ASCII characters become numeric entities): a
shell with no locale set garbled a/a/o on the way to the clipboard once, and
an entity can't be garbled by any copy/paste path or mail client.

To add another email (magic link, change email, invite...), add an entry to
TEMPLATES. Supabase fills in {{ .Token }}, {{ .ConfirmationURL }} etc. at send time.
"""
import pathlib

HERE = pathlib.Path(__file__).parent
LOGO_URL = "https://morninglist.app/email-logo.png"  # email-logo.png in the repo root
CORAL = "#F0654A"
TEXT = "#495057"
BODY_FONT = "'Karla',Helvetica,Arial,sans-serif"


# Shapes mirror the app's own screens (.primary-btn, .field input in style.css)
# so an email and the screen it leads to look like the same product.
def button(label, url):
    return (
        f'<table role="presentation" cellpadding="0" cellspacing="0" width="100%">'
        f'<tr><td align="center" style="border-radius:24px; background:{CORAL};">'
        f'<a href="{url}" style="display:block; padding:16px 32px; font-family:{BODY_FONT}; '
        f'font-size:18px; font-weight:700; color:#FFFFFF; text-decoration:none;">'
        f"{label}</a></td></tr></table>"
    )


def code_block(token):
    return (
        f'<table role="presentation" cellpadding="0" cellspacing="0" width="100%">'
        f'<tr><td align="center" style="border-radius:16px; background:#FFFFFF; border:2px solid #DEE2E6; padding:16px 12px;">'
        f'<span style="font-family:{BODY_FONT}; font-size:30px; font-weight:700; '
        f'letter-spacing:6px; color:#2B2D42;">{token}</span></td></tr></table>'
    )


def extra_row(html):
    return (
        f'<tr><td align="center" style="padding: 24px 0 0;">'
        f'<p style="margin:0; font-family:{BODY_FONT}; font-size:14px; line-height:1.5; color:{TEXT};">'
        f"{html}</p></td></tr>"
    )


def text_link(label, url):
    return f'<a href="{url}" style="color:{CORAL}; font-weight:700; text-decoration:none;">{label}</a>'


TEMPLATES = {
    "confirm-signup": dict(
        title="Bekräfta din e-post",
        body="Skriv in koden nedan i appen för att bekräfta din e-postadress.",
        action=code_block("{{ .Token }}"),
        extra=extra_row("Föredrar du en länk? " + text_link("Bekräfta med länk", "{{ .ConfirmationURL }}")),
        footnote="Skapade du inte det här kontot? Då kan du ignorera det här mejlet &mdash; "
                 "inget konto skapas utan koden eller länken ovan.",
    ),
    "reset-password": dict(
        title="Nytt lösenord",
        body="Vi fick en begäran om att återställa lösenordet för ditt Morgonlistan-konto. "
             "Klicka på knappen nedan för att välja ett nytt lösenord.",
        action=button("Återställ lösenord", "{{ .ConfirmationURL }}"),
        extra="",
        footnote="Bad du inte om det här? Då kan du ignorera mejlet &mdash; "
                 "inget ändras förrän någon klickar på länken ovan.",
    ),
}


def ascii_entities(s):
    return "".join(c if ord(c) < 128 else f"&#{ord(c)};" for c in s)


def main():
    layout = (HERE / "_layout.html").read_text(encoding="utf-8")
    for name, t in TEMPLATES.items():
        html = layout
        for slot, value in {
            "LOGO_URL": LOGO_URL,
            "TITLE": t["title"],
            "BODY": t["body"],
            "ACTION": t["action"],
            "EXTRA": t["extra"],
            "FOOTNOTE": t["footnote"],
        }.items():
            html = html.replace(f"[[{slot}]]", value)
        header = (
            f"<!-- GENERATED by build.py from _layout.html - edit those, not this file.\n"
            f"     Paste into Supabase: Authentication -> Email Templates -> {name}. -->\n"
        )
        (HERE / f"{name}.html").write_text(ascii_entities(header + html), encoding="ascii")
        print("wrote", f"{name}.html")


if __name__ == "__main__":
    main()
